### PR TITLE
Documentation Translated into Portuguese

### PR DESCRIPTION
**Pull request by ArthurSampaio**
Hi @auremoser @acabunoc !

I finished all the translation of this docs into portuguese (hard work), I think that may increases the Lusitanian origin study-groups and thus boost the open science practices around here.  

Do you want that I create a gitbook in portuguese too?

### CODE REVIEW

**Comment by ArthurSampaio** [comment]
I saw that Travis had made a mistake. When checking the error I saw that the same happens when the Travis VM tries to run the "gitbook install" command. I think there was some update on the system that changed some configuration files of the instance. Have any of you ever been through this?

**Comment by auremoser** [comment]
Hey @ArthurSampaio ! Thanks so much for these monumental edits and localization additions! You're so wonderful! 💯 :1st_place_medal: 

I wonder if the Study Group orientation is suffering from the same issue we encountered with the [Open Data Primers](https://mozillascience.github.io/open-data-primers/), where the version of node needed to be updated in `.travis.yml` because of changes that cause the travis build to fail. We haven't made an update to the Study Group Guide for a while, so it's entirely possible that is the issue. cc @stephwright + @acabunoc for additional opinions

You can see in [this issue](https://github.com/mozillascience/open-data-primers/commit/3dd083c60e6c37037f60eb40430ba0259a61a3dd) what I updated with the other book, updated node to version 6.0.

Maybe try that and see if Travis is happier? I can monitor the builds!

**Comment by ArthurSampaio** [comment]
Its fine now! Thank's for the help @auremoser

**Comment by auremoser** [comment]
Excellent @ArthurSampaio Thank you so much for your contribution. You rock! 🚀 🎸 🤗

**Pull request merged**
